include ../Makefile.inc

app.js: app.ps utils.js common-views.js note-view.ps channel-view.ps pattern-view.ps song-view.ps song-pattern-edit-select-view.ps instrument-select-view.ps tools-view.ps tools-sampler-view.ps tools-effects-view.ps tools-modular-view.ps sound-manager.ps macros.ps
